import AppKit
import ImageIO
import UniformTypeIdentifiers

/// The app that was frontmost when a copy was noticed.
nonisolated struct ClipboardSource: Equatable, Hashable, Sendable {
    var name: String?
    var bundleID: String?
}

/// A bounded, immutable reading of one pasteboard change. No pasteboard objects are retained.
nonisolated struct ClipboardCapture: Equatable, Sendable {
    enum Payload: Equatable, Hashable, Sendable {
        case text(String)
        case link(URL)
        case files([URL])
        /// Already downsampled and re-encoded by ``ClipboardImageEncoder``.
        case image(png: Data, width: Int, height: Int)
    }

    var payload: Payload
    var source = ClipboardSource()

    /// Content identity for skipping a repeated copy. Never persisted.
    var fingerprint: Int { payload.hashValue }
}

/// Turns the current pasteboard contents into a capture. Called only after the change count moved
/// and only while collecting is on.
@MainActor
enum ClipboardMuseumReader {
    enum Reading {
        case capture(ClipboardCapture)
        /// Raw image bytes that still need ``ClipboardImageEncoder`` off the main actor.
        case image(Data, ClipboardSource)
        case skipped
    }

    /// Markers from the nspasteboard.org convention that password managers and similar apps add
    /// to say "do not keep this". Items carrying any of them are never read.
    static let privateMarkers: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
    ]

    /// Checks advertised types first, then reads one representation. File URLs win over their
    /// thumbnail and name representations; images win over their text fallbacks.
    static func read(from pasteboard: NSPasteboard, source: ClipboardSource) -> Reading {
        let types = Set(pasteboard.types ?? [])
        guard !types.isEmpty, types.isDisjoint(with: privateMarkers) else { return .skipped }
        let items = pasteboard.pasteboardItems ?? []
        guard let first = items.first else { return .skipped }

        if types.contains(.fileURL) {
            let files = items.prefix(ClipboardMuseumLimits.maximumFiles).compactMap { item -> URL? in
                guard let string = item.string(forType: .fileURL), let url = URL(string: string), url.isFileURL,
                      url.host == nil || url.host == "" || url.host == "localhost" else { return nil }
                return url.standardizedFileURL
            }
            if !files.isEmpty { return .capture(ClipboardCapture(payload: .files(files), source: source)) }
        }
        if let type = first.availableType(from: [.png, .tiff]) {
            guard let data = first.data(forType: type), !data.isEmpty,
                  data.count <= ClipboardMuseumLimits.maximumImageInputBytes else { return .skipped }
            return .image(data, source)
        }
        if let string = first.string(forType: .string) {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return .skipped }
            if let url = link(trimmed) { return .capture(ClipboardCapture(payload: .link(url), source: source)) }
            // One character past the limit lets the store record that the text was cut.
            let bounded = String(string.prefix(ClipboardMuseumLimits.maximumTextCharacters + 1))
            return .capture(ClipboardCapture(payload: .text(bounded), source: source))
        }
        if let string = first.string(forType: .URL), let url = link(string) {
            return .capture(ClipboardCapture(payload: .link(url), source: source))
        }
        return .skipped
    }

    /// A single http or https URL with a host and no surrounding prose.
    nonisolated static func link(_ text: String) -> URL? {
        guard !text.contains(where: \.isWhitespace), let url = URL(string: text),
              let scheme = url.scheme?.lowercased(), scheme == "http" || scheme == "https",
              let host = url.host(), !host.isEmpty else { return nil }
        return url
    }
}

/// Decodes the first frame of a copied image and stores it as a bounded PNG.
nonisolated enum ClipboardImageEncoder {
    /// Runs ImageIO without touching AppKit, so it is safe off the main actor.
    ///
    /// - Returns: PNG bytes and pixel size after downsampling to
    ///   ``ClipboardMuseumLimits/maximumImageDimension``, or nil for unreadable or oversized images.
    static func png(from data: Data) -> (data: Data, width: Int, height: Int)? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil), CGImageSourceGetCount(source) > 0 else {
            return nil
        }
        // Read the header before decoding so a huge frame is refused without allocating it.
        if let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
           let width = (properties[kCGImagePropertyPixelWidth] as? NSNumber)?.intValue,
           let height = (properties[kCGImagePropertyPixelHeight] as? NSNumber)?.intValue {
            guard width > 0, height > 0, width * height <= ClipboardMuseumLimits.maximumImagePixels else { return nil }
        }
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: ClipboardMuseumLimits.maximumImageDimension,
            kCGImageSourceShouldCacheImmediately: true,
        ]
        guard let image = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else { return nil }
        let output = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(output as CFMutableData,
                                                                 UTType.png.identifier as CFString, 1, nil) else {
            return nil
        }
        CGImageDestinationAddImage(destination, image, nil)
        guard CGImageDestinationFinalize(destination) else { return nil }
        return (output as Data, image.width, image.height)
    }
}
